#! /usr/bin/env node
var WebDriver = require('./scripts/webdriver.js');
var DeployServer = require('./scripts/deployServer.js');
var fs = require('fs');
var program = require('commander');
var exec = require('child_process').exec;
var request = require('request');
var Report = require('./scripts/Report.js');

// Avoid SSL errors
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

// CONSTANTS
var TEST_FILE;
var EXPERIMENT_ID = new Date().getTime();
var EXPERIMENT_POST = "https://centauro.ls.etsiinf.upm.es:4444/security/experiment";
var CHORME_CONFIG_FILE = __dirname + '/extension/scripts/config.json';


// PROGRAM SETUP
program
  .version('0.0.1')
  .description("Security analyzer based on scopes required by any component")
  .arguments("<test_component>")
  .option("-c --config <files_list>", "Configuration file in JSON format")
  .action(function (file) { TEST_FILE = file; })
  .parse(process.argv);

// READ CONFIG FILE IF EXIST
var CONFIG = {};
if (program.config) {
  CONFIG = JSON.parse(fs.readFileSync(program.config, 'utf-8'));
}

// IF NOT CONFIG or FILE, RETURN HELp
if (!TEST_FILE && !CONFIG.files) {
  program.help();
  process.exit(1);
}



// MAIN
function main() {
  Report.generateReport(TEST_FILE, CONFIG).then(function () {
    process.exit(0);
  }, function (err) {
    console.error(err);
    process.exit(1);
  });
}
main();